---
- name: Desligamento de usuário
  hosts: winserver
  gather_facts: no
  tasks:
  
  - name: Removendo usuário no Active Directory
    win_domain_user:
      name: Joseph Climber
      #upn: jclimber@limasa.org.br
      state: absent

  - name: Removendo diretório pessoal na rede
    win_file:
      path: C:\Temp\jclimber
      state: absent  