- name: Criando usuário no Active Directory
  win_domain_user:
    name: "{{ nuser }} {{ nlastname }}"
    firstname: "{{ nuser }}"
    surname: "{{ nlastname }}"
    email: "{{ usermail }}"
    password: TEste.2010213g32
    state: present
    attributes:
      userPrincipalName: "{{ login }}@limasa.org.br"
      displayName: "{{ nuser }} {{ nlastname }}"
      title: Profissional
    path: OU=GOSD,OU=GESIN,DC=limasa,DC=org,DC=br

- name: Carregando informações do Template
  win_domain_user:
    name: "{{ nuser }} {{ nlastname }}"
    groups_action: add
    groups:
    - G_GESIN
    - G_GESIN_GOSD
    description: GOSD - Operação Data Center & Service Desk
    attributes:        
      sAMAccountName: "{{ login }}"
      department: GOSD - Operação Data Center & Service Desk
      physicalDeliveryOfficeName: GESIN - Suporte & Infraestrutura
      scriptPath: GESIN.bat
  ignore_errors: yes        