- name: Criando usuário no Active Directory
  win_domain_user:
    name: "{{ nuser }} {{ nlastname }}"
    firstname: "{{ nuser }}"
    surname: "{{ nlastname }}"
    email: "{{ usermail }}"
    password: TEste.2010213g32
    state: present
    attributes:
      userPrincipalName: "{{ login }}@limasa.org.br"
      displayName: "{{ nuser }} {{ nlastname }}"
      title: Profissional
    path: "{{ oupath }}" ##OU=FOO,OU=BAR,DC=limasa,DC=org,DC=br

- name: Carregando informações do Template
  win_domain_user:
    name: "{{ nuser }} {{ nlastname }}"
    groups_action: add
    groups:
    - FOO
    - BAR
    description: my descritpion
    attributes:        
      sAMAccountName: "{{ login }}"
      department: My_department ##FOO BAR - COMPANY CO
      physicalDeliveryOfficeName: COMPANY CO
      scriptPath: FOO.bat
  ignore_errors: yes        